photo-sorter:
  source-folder: "C:\\Users\\npitt\\Downloads\\匯出照片\\iCareFone\\Photo\\2025\\2025-11-09 21-15-04\\Bursts"
  destination-folder: "C:\\Users\\npitt\\Downloads\\匯出照片\\iCareFone\\Photo\\2025\\2025-11-09 21-15-04\\Sorted\\CameraRoll"
