photo-sorter:
  source-folder: "C:\\Users\\npitt\\Downloads\\匯出照片\\iCareFone\\Photo\\2025\\2025-11-09 21-47-17\\CameraRoll"
  destination-folder: "C:\\Users\\npitt\\Downloads\\匯出照片\\iCareFone\\Photo\\2025\\2025-11-09 21-47-17\\Una\\Sorted\\CameraRoll"
